################
#shiny app to simulate changes in n, cov(x,e)
#dc - 2.4.23
################
library(shiny)
library(ggplot2)
library(mvtnorm)
library(patchwork)

# Define UI for application that plots b, se
ui <- fluidPage(
  
  # Application title
  titlePanel("Simulating the OLS regression"),
  
  # Sidebar with a slider input for mean, sd 
  sidebarLayout(
    sidebarPanel(
      sliderInput("N",
                  "Sample size, N:",
                  min = 0,
                  max = 1500,
                  value = 20, step=100),
      br(),
      
      sliderInput("rhox1e",
                  label = HTML("&rho; (Cov(x1,&epsilon;)):"),
                  min = -1,
                  max = 1 ,
                  value = 0, step=.1),
      br(),
      
      sliderInput("rhox1x2",
                  label = "Cov(x1,x2)):",
                  min = -1,
                  max = 1,
                  value = 0, step=.1 )
    ),
    
    
    
    mainPanel(
      "OLS linear regression, data generated by",
      code("y = .5 + x1 + 2*x2 + e."),  
      "Simulation varies sample size, correlation of x1 and the error, and correlation
          or x1 and x2. Plots examine recovery of coefficients and standard errors.",
      
      # Output: Tabset w/ plot, summary, and table ----
      tabsetPanel(type = "tabs",
                  tabPanel("Over N", plotOutput("distPlot1")),
                  tabPanel("Over rho", plotOutput("distPlot2"))
      )
      
       
    ))
)


# Define server logic required to draw distributions
server <- function(input, output) {
  output$distPlot1 <- renderPlot({
    # generate parameters based on input$  from ui.R
    results <- data.frame ( var = character (0), coef = numeric(0), se = numeric (0), n = numeric (0))
    
    for(i in seq(10,input$N,10)) { 
      set.seed(12345)
      data <- tibble(
        X <- rnorm_multi(i, 3, 
                         mu=c(0, 0, 0), 
                         sd=1,
                         r = c(input$rhox1x2, input$rhox1e, 0.0),
                         varnames=c("x1", "x2", "e"))
      ) %>%
        mutate(y = .5 + 1*x1 + 2*x2 + e)
      
      mod <- (lm(y ~ x1 + x2, data=data))
      
      results[((i-9)*3-2):((i-9)*3),1:4] <- data.frame ( var = c("x0","x1","x2"), coef(summary(mod))[,1:2], i)
      
    }
    
    results <-data.frame(results, t=results$coef/results$se)
    
    
    p1 <- ggplot(data=results%>%filter(!is.na(n)), aes(x=n, y=coef, color=var)) +
      geom_line() +
      labs ( colour = NULL, x = "Sample Size", y =  "Estimated Coefficient" ) +
      theme ( legend.position = "bottom",
              legend.key = element_blank() ) 
    
    
    
    p2 <- ggplot(data=results%>%filter(!is.na(n)), aes(x=n, y=se, color=var)) +
      geom_line() +
      labs ( colour = NULL, x = "Sample Size", y =  "Estimated Standard Error" ) +
      theme ( legend.position = "bottom",
              legend.key = element_blank() )
    
    
    p1 | p2
  })
  
  output$distPlot2 <- renderPlot({
    # generate parameters based on input$  from ui.R
    resultsR <- data.frame ( var = character (0), coef = numeric(0), se = numeric (0), rho = numeric (0))
    
    j=1
    for(r in seq(-.95,.95,.01)) { 
      set.seed(12345)
      datar <- tibble(
        Xr <- rnorm_multi(input$N, 3, 
                         mu=c(0, 0, 0), 
                         sd=1,
                         r = c(input$rhox1x2, r, 0.0),
                         varnames=c("x1", "x2", "e"))
      ) %>%
        mutate(yr = .5 + 1*x1 + 2*x2 + e)
      
      modr <- (lm(yr ~ x1 + x2, data=datar))
      
      resultsR[((j)*3-2):((j)*3),1:4] <- data.frame ( var = c("x0","x1","x2"), coef(summary(modr))[,1:2], rho=r)
      
      j=j+1
    }
    
    resultsR <-data.frame(resultsR, t=resultsR$coef/resultsR$se)
    
    
    r1 <- ggplot(data=resultsR%>%filter(!is.na(rho)), aes(x=rho, y=coef, color=var)) +
      geom_line() +
      labs ( colour = NULL, x = "Correlation x1, e", y =  "Estimated Coefficient" ) +
      theme ( legend.position = "bottom",
              legend.key = element_blank() ) 
    
    
    
    r2 <- ggplot(data=resultsR%>%filter(!is.na(rho)), aes(x=rho, y=se, color=var)) +
      geom_line() +
      labs ( colour = NULL, x = "Correlation x1, e", y =  "Estimated Standard Error" ) +
      theme ( legend.position = "bottom",
              legend.key = element_blank() )
    
    
    r1 | r2
  })  

  
}


# Run the application 
shinyApp(ui = ui, server = server)
